color: yellow
fieldLayouts:
  032ab540-b968-4bd0-8dd0-2940d968a8bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:04:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a129d9bd-6b11-49e8-8178-4e2cf72c7f38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:07:02+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 502f127c-83b4-4294-9a5d-d6bce8113ecb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:07:02+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df477209-06cb-4584-8832-7a449484b199
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e9fd0b9c-68cd-431f-a280-c11ce8cf3c92
        userCondition: null
handle: categories
hasTitleField: true
icon: table-list
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
