color: yellow
fieldLayouts:
  7c20b03d-b7fe-4cc2-84cb-6a5e7bf6f289:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:04:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23cf4f85-0ca5-486e-be2b-a65a54b365e8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:07:13+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3431841-378a-4b28-bda9-b7a0f06d30d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8677c4bc-1a4f-44f9-a774-e780dd114c64
        userCondition: null
handle: locations
hasTitleField: true
icon: map-pin
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
