columnSuffix: null
handle: category
instructions: null
name: Category
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:bdab4999-af94-4a07-bdb5-9360a6e74d38' # Categories
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
