columnSuffix: null
handle: city
instructions: null
name: City
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:3df8ad16-15d5-4d19-8587-3829eff96524' # Locations
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
