defaultPlacement: end
enableVersioning: true
entryTypes:
  - d802ba46-f1b9-4109-8f14-d404c2287b1a # Navigation
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: c17b2d77-b2aa-4b9d-9962-34c9412c7a26
type: structure
